server:
  port: 8501

spring:
  # 配置数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.71.136:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
#    password: 1234
    password: llllllll
  # Redis的相关配置
  data:
    redis:
#      host: 192.168.71.136
      host: localhost
      port: 6379
      password: llllllll
  servlet:
    multipart:
      max-file-size: 2MB


# mybatis的配置
mybatis:
  # mybatis-config.xml配置文件位置
  config-location: classpath:/mybatis-config.xml
  # 扫描的mapper.xml文件位置
  mapper-locations: classpath:/mapper/*/*.xml

# 自定义配置,用于拦截器的拦截范围信息
spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
# 上传文件Minio-自定义配置
  minio:
    endpointUrl: http://127.0.0.1:9000
    accessKey: minioadmin
    secreKey: minioadmin
    bucketName: spzx-bucket
